version: '3.8'

services:
  api:
    container_name: scalewize-librechat-api
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspaces
    volumes:
      - ./images:/workspaces/client/public/images
      - ./client/dist:/workspaces/client/dist:ro
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MONGO_URI=${MONGO_URI}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ENABLE_USAGE_TRACKING=true
      - LOG_LEVEL=info
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
      - rag_api
    restart: always
    command: sh -c "npm install && npm run build:data-provider && npm run build:data-schemas && npm run build:api && npm run backend"

  mongodb:
    container_name: scalewize-mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

  meilisearch:
    container_name: scalewize-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data

  vectordb:
    container_name: scalewize-vectordb
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rag_api:
    container_name: scalewize-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb

  nginx:
    container_name: scalewize-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: always

volumes:
  mongodb_data:
  meili_data:
  postgres_data:
