[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python3", "make", "gcc"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = [
    "npm run build:data-provider",
    "npm run build:data-schemas", 
    "npm run build:api",
    "npm run frontend"
]

[phases.start]
cmd = "npm run backend"

[variables]
NODE_ENV = "production"