[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/start.sh"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.variables]
HTTPS_ENABLED = "false"
HOST = "0.0.0.0"
PORT = "8080"
CONFIG_PATH = "/app/librechat.yaml"
JWT_ENABLED = "true"
JWT_SECRET = "${JWT_SECRET}"
JWT_REFRESH_SECRET = "${JWT_REFRESH_SECRET}"
MCP_SERVERS_ENABLED = "true"
MCP_SERVERS_CONFIG = "${MCP_SERVERS_CONFIG}"

[deploy.healthcheck]
port = 8080
path = "/health"
timeout = 30
interval = 10
retries = 3 