[build]
builder = "DOCKERFILE"
dockerfilePath = ".devcontainer/Dockerfile"

[deploy]
startCommand = "npm install && npm run build:data-provider && npm run build:data-schemas && npm run build:api && npm run backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.healthcheck]
path = "/api/health"
timeout = 600
interval = 30
retries = 5 