[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.variables]
HTTPS_ENABLED = "false"
CONFIG_PATH = "/app/librechat.yaml"
JWT_ENABLED = "true"
JWT_SECRET = "${JWT_SECRET}"
JWT_REFRESH_SECRET = "${JWT_REFRESH_SECRET}"

[deploy.healthcheck]
port = 8080
path = "/health"
timeout = 600
interval = 30
retries = 5 