[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.variables]
HTTPS_ENABLED = "false"

[deploy.healthcheck]
port = 8080

[deploy.healthcheck]
path = "/api/health"
timeout = 600
interval = 30
retries = 5 