[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.variables]
NODE_ENV = "production"
PORT = "3001"
MCP_TRANSPORT = "sse"

[deploy.healthcheck]
port = 3001
path = "/health"
timeout = 30
interval = 10
retries = 3 